public class Constants
{
    public static string QUESTION_VALIDATION='Please enter valid question or problem to submit.';
    public static string PORTAL_HOMEPAGE='/candidateportal'; //Replace this with your actual portal name
    
    public static string REFERRAL_ALERT_EMAILTEMPLATE='Recruiter_Referral_Email_template';
    
    public static string REFERRAL_AGENT_EMAIL_BLAST='Referal_Agent_Email_Alert';
    
    public static string NEW_REQUISITION_EMAIL_ALERT='New_Requisition_Email_Alert';
}